VL\SiteBundle\Entity\Comment:
    properties:
        # ...
        file:
            - Image: ~
        name:
            - NotBlank: ~
        email:
            - NotBlank: ~
        url:
            - Url: ~